### ISSUE TITLE
Discuss awesome criteria

### ISSUE THREAD

**Issue by faroit** [faroit/awesome-python-audio-research#2]
## Awesome Criteria (proposal)

* The package is actively maintained
* Ideally it runs on python 2.x and python 3
* The package/algorithm is generic and therefore useful for more than reproducing a single publication
* package is listed on pypi

**Comment by faroit** [comment]
paging @fzalkow @nils-werner

**Comment by fzalkow** [comment]
* Not sure about "actively maintained"... If it is a really cool package, maybe new maintainers will by found due to this list! There could a list of non-maintained packages at the bottom? 
* I am strongly against Python 2 AND 3 compatibility as criteria for this list!
* "generic" +1

**Comment by faroit** [comment]
> There could a list of non-maintained packages at the bottom?

or put a warning if its not maintained

> I am strongly against Python 2 AND 3

maybe then a warning, too if it only runs on 2 OR 3

what about the pypi criterion?

**Comment by faroit** [comment]
@fzalkow any suggestion which packages would get a ⭐️ to show users that these are very well used and tested?

I would propose a minimum number of github stars + contributions

**Comment by fzalkow** [comment]
Not sure about this, but I'd say, stars only? For example, if a project has been developed on SourceForge for long time and was recently moved to Github, there could be a small amount of commits. 

Download counts could also be an option. But stars only would be reasonable for me.

**Comment by faroit** [comment]
awesome criteria was added [here](https://github.com/faroit/awesome-python-audio-research/blob/master/CONTRIBUTING.md)
